#!/bin/bash

set -e

DAEMON=/opt/php/{{.var__pkgname}}/sbin/php-fpm
PIDFILE=/opt/php/{{.var__pkgname}}/var/run/php-fpm.pid
DAEMON_ARGS="-c /opt/php/{{.var__pkgname}}/etc --daemonize"
NAME=$(basename $DAEMON)


start() {
    if pidof $NAME; then
        exit 0;
    fi
    $DAEMON $DAEMON_ARGS --pid $PIDFILE
    retval=$?
    return $retval
}

stop() {
    if [ -f "$PIDFILE" ]; then
        pid=$(cat "$PIDFILE")
        if [ -d "/proc/$pid" ]; then
            kill $pid
        fi
        rm -f $PIDFILE
    fi
    sleep 1
}

reload() {
    pid=$(cat "$PIDFILE")
    kill -USR2 $pid
}

status() {
    if [ -f "$PIDFILE" ]; then
        pid=$(cat "$PIDFILE")
        if [ -d "/proc/$pid" ]; then
            echo "running" && exit 0
        fi
    fi
    echo "stopped"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    reload)
        reload
        ;;
    status)
        status
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 2
esac

